version: '3.8'

services:
  builder:
    build: ./infra/builder
    user: "${UID}:${GID}"
    volumes:
    - ./:/app
    - ./.cache:/go/.cache
    ports:
      - 8000:8080
    environment:
      GOCACHE: /go/.cache
      CGO_ENABLED: 0

  testData:
    image: nginx
    volumes:
      - ./test_data:/usr/share/nginx/html
    ports:
      - 8080:80

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${APP_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${APP_MONGO_PASS}

  app1:
    build: ./src
    depends_on:
      - mongo
    env_file:
      - .env

  app2:
    build: ./src
    depends_on:
      - mongo
    env_file:
      - .env

  balancer:
    image: nginx
    ports:
      - 6000:6000
    depends_on:
      - app1
      - app2
    volumes:
      - ./infra/balancer/default.conf:/etc/nginx/conf.d/default.conf