// Code generated by mockery v2.4.0. DO NOT EDIT.

package domain

import (
	context "context"

	model "github.com/nejtr0n/api_example/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MockApiService is an autogenerated mock type for the ApiService type
type MockApiService struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: ctx, url
func (_m *MockApiService) Fetch(ctx context.Context, url string) (int64, error) {
	ret := _m.Called(ctx, url)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, url)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, limit, offset, sortBy, sortOrder
func (_m *MockApiService) List(ctx context.Context, limit int64, offset int64, sortBy string, sortOrder int) ([]*model.Product, error) {
	ret := _m.Called(ctx, limit, offset, sortBy, sortOrder)

	var r0 []*model.Product
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, int) []*model.Product); ok {
		r0 = rf(ctx, limit, offset, sortBy, sortOrder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, string, int) error); ok {
		r1 = rf(ctx, limit, offset, sortBy, sortOrder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
