// Code generated by mockery v2.4.0. DO NOT EDIT.

package services

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockCsvLoader is an autogenerated mock type for the CsvLoader type
type MockCsvLoader struct {
	mock.Mock
}

// Load provides a mock function with given fields: _a0
func (_m *MockCsvLoader) Load(_a0 string) (io.ReadCloser, error) {
	ret := _m.Called(_a0)

	var r0 io.ReadCloser
	if rf, ok := ret.Get(0).(func(string) io.ReadCloser); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
