// Code generated by mockery v2.4.0. DO NOT EDIT.

package services

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockCsvFileDownloader is an autogenerated mock type for the CsvLoader type
type MockCsvFileDownloader struct {
	mock.Mock
}

// Load provides a mock function with given fields: url
func (_m *MockCsvFileDownloader) Load(url string) (io.ReadCloser, error) {
	ret := _m.Called(url)

	var r0 io.ReadCloser
	if rf, ok := ret.Get(0).(func(string) io.ReadCloser); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
