// Code generated by mockery v2.4.0. DO NOT EDIT.

package services

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockCsvReaderFactory is an autogenerated mock type for the CsvReaderFactory type
type MockCsvReaderFactory struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MockCsvReaderFactory) Execute(_a0 io.ReadCloser) (CsvReader, error) {
	ret := _m.Called(_a0)

	var r0 CsvReader
	if rf, ok := ret.Get(0).(func(io.ReadCloser) CsvReader); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(CsvReader)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(io.ReadCloser) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
