// Code generated by mockery v2.4.0. DO NOT EDIT.

package services

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	model "github.com/nejtr0n/api_example/domain/model"
)

// MockCsvFileParser is an autogenerated mock type for the CsvParser type
type MockCsvFileParser struct {
	mock.Mock
}

// Parse provides a mock function with given fields: ctx, pipe, data
func (_m *MockCsvFileParser) Parse(ctx context.Context, pipe chan *model.Product, data io.ReadCloser) error {
	ret := _m.Called(ctx, pipe, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, chan *model.Product, io.ReadCloser) error); ok {
		r0 = rf(ctx, pipe, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
